# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='N/A', max_length=400),
            preserve_default=False,
        ),
    ]
