# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_blog', '0006_auto_20171125_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='post',
            name='method',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='cooking_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.TextField(max_length=400),
        ),
    ]
